name: Deno CI

on:
  pull_request:
    branches:
      - main

jobs:
  deno-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check formatting
        run: deno fmt --check

      - name: Lint code
        run: deno lint

      - name: Run tests with coverage
        run: |
          deno test --allow-all --coverage=coverage
          deno coverage coverage --lcov > coverage.lcov

      - name: Upload coverage report (optional)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage.lcov
